//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryInfoSystemLite_NikolaevDV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.User = new HashSet<User>();
        }
    
        public int BookID { get; set; }
        public string NameBook { get; set; }
        public Nullable<int> Annotation { get; set; }
        public string Description { get; set; }
        public Nullable<int> Genre { get; set; }
        public int Quanity { get; set; }
        public Nullable<int> Author { get; set; }
        public Nullable<int> PublishHouse { get; set; }
        public int TomeNumber { get; set; }
        public int TomeQuanity { get; set; }
        public Nullable<int> PublicType { get; set; }
        public Nullable<int> Language { get; set; }
        public Nullable<int> LanguageTranstation { get; set; }
        public string Redaction { get; set; }
        public Nullable<int> ReleaseYear { get; set; }
        public string BookCode { get; set; }
        public Nullable<int> ReadyFIssuanse { get; set; }
    
        public virtual Annotation Annotation1 { get; set; }
        public virtual Author Author1 { get; set; }
        public virtual Genre Genre1 { get; set; }
        public virtual Language Language1 { get; set; }
        public virtual LanguageTranslation LanguageTranslation { get; set; }
        public virtual PublicType PublicType1 { get; set; }
        public virtual PublishHouse PublishHouse1 { get; set; }
        public virtual ReadyIssuance ReadyIssuance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
