//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryInfoSystemLite_NikolaevDV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookID { get; set; }
        public string Name { get; set; }
        public int Genre { get; set; }
        public string Author { get; set; }
        public int VolumeNumber { get; set; }
        public string VolumeCity { get; set; }
        public string VolumeQuanity { get; set; }
        public int PublicType { get; set; }
        public Nullable<int> Language { get; set; }
        public Nullable<int> LanguageTranstation { get; set; }
        public string Editorial { get; set; }
        public int ReleaseYear { get; set; }
        public Nullable<int> Readers { get; set; }
    
        public virtual Genre Genre1 { get; set; }
        public virtual Language Language1 { get; set; }
        public virtual LanguageTranslation LanguageTranslation { get; set; }
        public virtual PublicType PublicType1 { get; set; }
        public virtual Readers Readers1 { get; set; }
    }
}
