//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryInfoSystemLite_NikolaevDV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public int QueueID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> BookID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
