//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryInfoSystemLite_NikolaevDV
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Addrees { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> Book { get; set; }
        public Nullable<int> Appeals { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public int RoleID { get; set; }
    
        public virtual Appeals Appeals1 { get; set; }
        public virtual Book Book1 { get; set; }
        public virtual Role Role { get; set; }
    }
}
